swipe:
    4:
        left:
            command: 'xdotool key alt+ctrl+Left'
        right:
            command: 'xdotool key alt+ctrl+Right'
    3:
        left:
            command: 'xdotool key alt+Left'
        right:
            command: 'xdotool key alt+Right'
